
-- Lion Automotive Part - e-commerce database
-- Run this in Supabase SQL Editor.
create extension if not exists pgcrypto;

create table if not exists public.products (
  id bigint generated by default as identity primary key,
  legacy_id bigint unique,
  sku text unique not null,
  name text not null,
  description text,
  compatibility text,
  category text,
  brand text,
  price integer not null default 0 check (price >= 0),
  original_price integer check (original_price is null or original_price >= 0),
  stock integer not null default 0 check (stock >= 0),
  image text,
  shopee_url text,
  rating numeric(3,2),
  sold_count text,
  badge text,
  active boolean not null default true,
  source text not null default 'manual',
  source_updated_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists products_active_idx on public.products(active);
create index if not exists products_category_idx on public.products(category);
create index if not exists products_brand_idx on public.products(brand);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  order_number text unique not null,
  customer_name text not null,
  customer_email text,
  customer_phone text not null,
  shipping_address text not null,
  shipping_city text,
  shipping_postal_code text,
  shipping_method text,
  shipping_cost integer not null default 0,
  subtotal integer not null default 0,
  total integer not null default 0,
  status text not null default 'pending'
    check (status in ('pending','paid','processing','shipped','completed','cancelled','expired')),
  payment_status text not null default 'pending'
    check (payment_status in ('pending','paid','failed','expired','cancelled')),
  payment_provider text,
  payment_reference text,
  payment_token text,
  notes text,
  expires_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  product_id bigint not null references public.products(id),
  sku text not null,
  product_name text not null,
  unit_price integer not null,
  quantity integer not null check (quantity > 0),
  line_total integer not null
);

create index if not exists order_items_order_idx on public.order_items(order_id);
create index if not exists orders_status_idx on public.orders(status);
create index if not exists orders_created_idx on public.orders(created_at desc);

create table if not exists public.inventory_sync_logs (
  id bigint generated by default as identity primary key,
  source text not null,
  status text not null,
  updated_count integer not null default 0,
  skipped_count integer not null default 0,
  error_count integer not null default 0,
  message text,
  created_at timestamptz not null default now()
);

create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists products_touch on public.products;
create trigger products_touch before update on public.products
for each row execute function public.touch_updated_at();

drop trigger if exists orders_touch on public.orders;
create trigger orders_touch before update on public.orders
for each row execute function public.touch_updated_at();

alter table public.products enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.inventory_sync_logs enable row level security;

drop policy if exists "public can read active products" on public.products;
create policy "public can read active products"
on public.products for select to anon, authenticated
using (active = true);

-- Orders are created/changed only by Edge Functions using the server secret.
-- Customers do not get direct table write access.
revoke all on public.orders from anon, authenticated;
revoke all on public.order_items from anon, authenticated;
revoke all on public.inventory_sync_logs from anon, authenticated;

-- Atomic order creation + stock decrement.
create or replace function public.create_order(
  p_customer_name text,
  p_customer_email text,
  p_customer_phone text,
  p_shipping_address text,
  p_shipping_city text,
  p_shipping_postal_code text,
  p_shipping_method text,
  p_shipping_cost integer,
  p_notes text,
  p_items jsonb
)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  item jsonb;
  p record;
  v_order_id uuid := gen_random_uuid();
  v_order_number text := 'LAP-' || to_char(now(),'YYYYMMDD') || '-' || upper(substr(replace(v_order_id::text,'-',''),1,8));
  v_subtotal integer := 0;
  v_qty integer;
  v_line integer;
begin
  if jsonb_typeof(p_items) <> 'array' or jsonb_array_length(p_items) = 0 then
    raise exception 'Cart is empty';
  end if;

  -- Lock and validate every product.
  for item in select * from jsonb_array_elements(p_items)
  loop
    v_qty := greatest(0, (item->>'quantity')::integer);
    if v_qty <= 0 then raise exception 'Invalid quantity'; end if;

    select * into p from public.products
    where id = (item->>'product_id')::bigint and active = true
    for update;

    if not found then raise exception 'Product not found'; end if;
    if p.stock < v_qty then raise exception 'Insufficient stock for SKU %', p.sku; end if;

    v_line := p.price * v_qty;
    v_subtotal := v_subtotal + v_line;
  end loop;

  insert into public.orders(
    id, order_number, customer_name, customer_email, customer_phone,
    shipping_address, shipping_city, shipping_postal_code, shipping_method,
    shipping_cost, subtotal, total, status, payment_status, notes, expires_at
  ) values (
    v_order_id, v_order_number, trim(p_customer_name), nullif(trim(p_customer_email),''),
    trim(p_customer_phone), trim(p_shipping_address), nullif(trim(p_shipping_city),''),
    nullif(trim(p_shipping_postal_code),''), nullif(trim(p_shipping_method),''),
    greatest(0,p_shipping_cost), v_subtotal, v_subtotal + greatest(0,p_shipping_cost),
    'pending','pending',nullif(trim(p_notes),''), now() + interval '30 minutes'
  );

  for item in select * from jsonb_array_elements(p_items)
  loop
    select * into p from public.products where id = (item->>'product_id')::bigint for update;
    v_qty := (item->>'quantity')::integer;
    v_line := p.price * v_qty;

    insert into public.order_items(order_id, product_id, sku, product_name, unit_price, quantity, line_total)
    values (v_order_id, p.id, p.sku, p.name, p.price, v_qty, v_line);

    update public.products
      set stock = stock - v_qty,
          source = 'website-order'
    where id = p.id;
  end loop;

  return jsonb_build_object(
    'order_id', v_order_id,
    'order_number', v_order_number,
    'subtotal', v_subtotal,
    'total', v_subtotal + greatest(0,p_shipping_cost),
    'expires_at', now() + interval '30 minutes'
  );
end;
$$;

-- Refund stock when an unpaid order is cancelled/expired.
create or replace function public.release_order_stock(p_order_id uuid)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare r record;
begin
  for r in
    select product_id, quantity
    from public.order_items
    where order_id = p_order_id
  loop
    update public.products set stock = stock + r.quantity where id = r.product_id;
  end loop;
end;
$$;
